apiVersion: 1

datasources:
  - name: Grafana Tempo
    type: tempo
    access: proxy
    url: http://tempo:3100
    isDefault: false
    uid: tempo
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'Loki'
        tags:
          - 'service.name'
          - 'traceId'
      nodeGraph:
        enabled: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    editable: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId":"([^"]+)"'
          url: $${__url}
          urlDisplayLabel: View Trace
          datasourceUid: tempo
        - name: Trace ID (HTTP header)
          matcherRegex: '"X-Trace-Id":"([^"]+)"'
          url: $${__url}
          urlDisplayLabel: View Trace
          datasourceUid: tempo
