apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.monitoring:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      timeInterval: 15s
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Bearer ${PROMETHEUS_TOKEN}
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki.monitoring:3100
    jsonData:
      maxLines: 500
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"([^"]+)"'
          url: '${DS_LOKI}//quote?expr={env="${env}"}|="trace_id"="$${__value}"'
        - name: pod
          matcherRegex: '"pod":"([^"]+)"'
          url: '${DS_LOKI}//quote?expr={env="${env}",namespace="${namespace}"}|="pod"="$${__value}"'
        - name: application_id
          matcherRegex: '"application_id":"([^"]+)"'
          url: '${DS_LOKI}//quote?expr={env="${env}"}|="application_id"="$${__value}"'
    editable: false

  - name: Tempo (Tracing)
    type: tempo
    access: proxy
    url: http://tempo.monitoring:3100
    jsonData:
      tracesToLogs:
        datasourceUid: Loki
        tags:
          - pod
          - namespace
          - trace_id
      serviceMap:
        datasourceUid: Prometheus
    editable: false

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager.monitoring:9093
    jsonData:
      implementation: prometheus
    editable: false

  - name: PrometheusLowFreq
    type: prometheus
    access: proxy
    url: http://prometheus.monitoring:9090
    jsonData:
      httpMethod: POST
      timeInterval: 60s
    editable: false
