export enum Permission {
  APPLICATION_CREATE = 'application:create',
  APPLICATION_READ = 'application:read',
  APPLICATION_UPDATE = 'application:update',
  APPLICATION_DELETE = 'application:delete',
  APPLICATION_SUBMIT = 'application:submit',
  APPLICATION_ASSIGN_OFFICER = 'application:assign_officer',
  APPLICATION_READ_ALL = 'application:read_all',

  KYC_INITIATE = 'kyc:initiate',
  KYC_VERIFY = 'kyc:verify',
  KYC_READ = 'kyc:read',

  DOCUMENT_UPLOAD = 'document:upload',
  DOCUMENT_READ = 'document:read',
  DOCUMENT_DELETE = 'document:delete',
  DOCUMENT_REVIEW = 'document:review',
  DOCUMENT_WATERMARK = 'document:watermark',

  DECISION_TRIGGER = 'decision:trigger',
  DECISION_READ = 'decision:read',
  DECISION_OVERRIDE_REQUEST = 'decision:override_request',
  DECISION_OVERRIDE_APPROVE = 'decision:override_approve',

  BUREAU_PULL = 'bureau:pull',
  BUREAU_READ = 'bureau:read',

  DISBURSEMENT_INITIATE = 'disbursement:initiate',
  DISBURSEMENT_READ = 'disbursement:read',
  DISBURSEMENT_APPROVE = 'disbursement:approve',

  SANCTION_LETTER_VIEW = 'sanction_letter:view',
  SANCTION_LETTER_GENERATE = 'sanction_letter:generate',
  LOAN_AGREEMENT_VIEW = 'loan_agreement:view',
  LOAN_AGREEMENT_GENERATE = 'loan_agreement:generate',
  LOAN_AGREEMENT_SIGN = 'loan_agreement:sign',

  POLICY_VIEW = 'policy:view',
  POLICY_MANAGE = 'policy:manage',
  POLICY_COMPARE = 'policy:compare',

  USER_MANAGE = 'user:manage',
  USER_READ = 'user:read',
  USER_CREATE = 'user:create',

  PARTNER_APPROVE = 'partner:approve',
  PARTNER_READ = 'partner:read',
  PARTNER_MANAGE = 'partner:manage',

  COMMISSION_VIEW = 'commission:view',
  COMMISSION_PROCESS = 'commission:process',

  AUDIT_READ = 'audit:read',
  COMPLIANCE_VIEW = 'compliance:view',

  DASHBOARD_VIEW = 'dashboard:view',
  STATS_READ = 'stats:read',
}

export const ROLE_PERMISSION_MAP: Record<string, Permission[]> = {
  APPLICANT: [
    Permission.APPLICATION_CREATE,
    Permission.APPLICATION_READ,
    Permission.APPLICATION_UPDATE,
    Permission.APPLICATION_SUBMIT,
    Permission.KYC_INITIATE,
    Permission.KYC_VERIFY,
    Permission.KYC_READ,
    Permission.DOCUMENT_UPLOAD,
    Permission.DOCUMENT_READ,
    Permission.SANCTION_LETTER_VIEW,
    Permission.LOAN_AGREEMENT_VIEW,
    Permission.DASHBOARD_VIEW,
  ],

  LOAN_OFFICER: [
    Permission.APPLICATION_CREATE,
    Permission.APPLICATION_READ,
    Permission.APPLICATION_UPDATE,
    Permission.APPLICATION_DELETE,
    Permission.APPLICATION_SUBMIT,
    Permission.APPLICATION_ASSIGN_OFFICER,
    Permission.APPLICATION_READ_ALL,
    Permission.KYC_INITIATE,
    Permission.KYC_VERIFY,
    Permission.KYC_READ,
    Permission.DOCUMENT_UPLOAD,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_DELETE,
    Permission.DOCUMENT_REVIEW,
    Permission.DOCUMENT_WATERMARK,
    Permission.DECISION_READ,
    Permission.DECISION_TRIGGER,
    Permission.BUREAU_READ,
    Permission.BUREAU_PULL,
    Permission.SANCTION_LETTER_VIEW,
    Permission.SANCTION_LETTER_GENERATE,
    Permission.LOAN_AGREEMENT_VIEW,
    Permission.LOAN_AGREEMENT_GENERATE,
    Permission.LOAN_AGREEMENT_SIGN,
    Permission.DASHBOARD_VIEW,
    Permission.STATS_READ,
  ],

  CREDIT_ANALYST: [
    Permission.APPLICATION_READ_ALL,
    Permission.APPLICATION_ASSIGN_OFFICER,
    Permission.KYC_READ,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_REVIEW,
    Permission.DOCUMENT_WATERMARK,
    Permission.DECISION_READ,
    Permission.DECISION_TRIGGER,
    Permission.DECISION_OVERRIDE_REQUEST,
    Permission.BUREAU_READ,
    Permission.BUREAU_PULL,
    Permission.SANCTION_LETTER_VIEW,
    Permission.SANCTION_LETTER_GENERATE,
    Permission.LOAN_AGREEMENT_VIEW,
    Permission.LOAN_AGREEMENT_GENERATE,
    Permission.LOAN_AGREEMENT_SIGN,
    Permission.POLICY_VIEW,
    Permission.DASHBOARD_VIEW,
    Permission.STATS_READ,
  ],

  BRANCH_MANAGER: [
    Permission.APPLICATION_READ_ALL,
    Permission.APPLICATION_ASSIGN_OFFICER,
    Permission.KYC_READ,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_REVIEW,
    Permission.DOCUMENT_WATERMARK,
    Permission.DECISION_READ,
    Permission.DECISION_TRIGGER,
    Permission.DECISION_OVERRIDE_REQUEST,
    Permission.DECISION_OVERRIDE_APPROVE,
    Permission.BUREAU_READ,
    Permission.BUREAU_PULL,
    Permission.DISBURSEMENT_APPROVE,
    Permission.SANCTION_LETTER_VIEW,
    Permission.SANCTION_LETTER_GENERATE,
    Permission.LOAN_AGREEMENT_VIEW,
    Permission.LOAN_AGREEMENT_GENERATE,
    Permission.LOAN_AGREEMENT_SIGN,
    Permission.POLICY_VIEW,
    Permission.POLICY_COMPARE,
    Permission.USER_READ,
    Permission.DASHBOARD_VIEW,
    Permission.STATS_READ,
    Permission.AUDIT_READ,
  ],

  ZONAL_CREDIT_HEAD: [
    Permission.APPLICATION_READ_ALL,
    Permission.APPLICATION_ASSIGN_OFFICER,
    Permission.KYC_READ,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_REVIEW,
    Permission.DECISION_READ,
    Permission.DECISION_TRIGGER,
    Permission.DECISION_OVERRIDE_REQUEST,
    Permission.DECISION_OVERRIDE_APPROVE,
    Permission.BUREAU_READ,
    Permission.BUREAU_PULL,
    Permission.DISBURSEMENT_APPROVE,
    Permission.SANCTION_LETTER_VIEW,
    Permission.LOAN_AGREEMENT_VIEW,
    Permission.POLICY_VIEW,
    Permission.POLICY_COMPARE,
    Permission.USER_READ,
    Permission.DASHBOARD_VIEW,
    Permission.STATS_READ,
    Permission.AUDIT_READ,
    Permission.COMPLIANCE_VIEW,
  ],

  COMPLIANCE_OFFICER: [
    Permission.APPLICATION_READ_ALL,
    Permission.KYC_READ,
    Permission.DOCUMENT_READ,
    Permission.DECISION_READ,
    Permission.BUREAU_READ,
    Permission.AUDIT_READ,
    Permission.COMPLIANCE_VIEW,
    Permission.STATS_READ,
  ],

  SYSTEM: [
    Object.values(Permission),
  ],

  ADMIN: [
    Object.values(Permission),
  ],
};

export function getScopesForRole(role: string): string[] {
  return ROLE_PERMISSION_MAP[role] || [];
}
